import type { GuestKeyField } from "@/lib/guest-keys/types";

export const GUEST_KEY_FIELDS: GuestKeyField[] = [
  {
    key: "CHATTERBOX_API_URL",
    label: "Chatterbox API URL",
    description: "Base URL of your Chatterbox TTS deployment (Modal or self-hosted).",
    required: true,
    type: "url",
    placeholder: "https://your-app.modal.run",
    feature: "tts",
  },
  {
    key: "CHATTERBOX_API_KEY",
    label: "Chatterbox API key",
    description: "Sent as the x-api-key header to your Chatterbox service.",
    required: true,
    type: "password",
    feature: "tts",
  },
  {
    key: "CHATTERBOX_MULTILINGUAL_API_URL",
    label: "Multilingual TTS URL (optional)",
    description: "Endpoint for 23-language voice cloning. Leave blank to skip multilingual.",
    type: "url",
    placeholder: "https://your-multilingual.modal.run",
    feature: "tts",
  },
  {
    key: "TRANSLATE_PROVIDER",
    label: "Translation provider",
    description: "Which service powers Live Translation on the dashboard.",
    type: "select",
    options: [
      { value: "", label: "None / use server default" },
      { value: "libretranslate", label: "LibreTranslate" },
      { value: "google", label: "Google Cloud Translation" },
      { value: "deepl", label: "DeepL" },
    ],
    feature: "translation",
  },
  {
    key: "LIBRETRANSLATE_URL",
    label: "LibreTranslate URL",
    description: "Base URL when using LibreTranslate (no trailing slash).",
    type: "url",
    placeholder: "http://localhost:5000",
    feature: "translation",
  },
  {
    key: "LIBRETRANSLATE_API_KEY",
    label: "LibreTranslate API key",
    description: "Optional if your instance does not require a key.",
    type: "password",
    feature: "translation",
  },
  {
    key: "LIBRETRANSLATE_LANGUAGE_IDS",
    label: "LibreTranslate language ids",
    description: "Comma-separated ids (e.g. en,es,fr) when using --load-only.",
    placeholder: "en,es,fr,de",
    feature: "translation",
  },
  {
    key: "GOOGLE_TRANSLATE_API_KEY",
    label: "Google Translate API key",
    description: "Cloud Translation API key when provider is Google.",
    type: "password",
    feature: "translation",
  },
  {
    key: "TRANSLATE_DEEPL_API_KEY",
    label: "DeepL API key",
    description: "DeepL auth key when provider is DeepL.",
    type: "password",
    feature: "translation",
  },
  {
    key: "FISH_API_KEY",
    label: "Fish Audio API key",
    description: "Realtime TTS for the voice agent.",
    type: "password",
    feature: "voice-agent",
  },
  {
    key: "VOICE_AGENT_LLM_PROVIDER",
    label: "Voice agent LLM",
    description: "Chat model provider for /voice-agent.",
    type: "select",
    options: [
      { value: "", label: "Use server default" },
      { value: "openai", label: "OpenAI" },
      { value: "gemini", label: "Gemini" },
    ],
    feature: "voice-agent",
  },
  {
    key: "OPENAI_API_KEY",
    label: "OpenAI API key",
    description: "For voice-agent chat when provider is OpenAI.",
    type: "password",
    feature: "voice-agent",
  },
  {
    key: "OPENAI_MODEL",
    label: "OpenAI model",
    description: "Optional model id (default gpt-4o-mini).",
    placeholder: "gpt-4o-mini",
    feature: "voice-agent",
  },
  {
    key: "GEMINI_API_KEY",
    label: "Gemini API key",
    description: "Google AI Studio key when provider is Gemini.",
    type: "password",
    feature: "voice-agent",
  },
  {
    key: "GEMINI_MODEL",
    label: "Gemini model",
    description: "Optional model id (default gemini-2.0-flash).",
    placeholder: "gemini-2.0-flash",
    feature: "voice-agent",
  },
];

export const GUEST_HOSTED_KEYS_INFO = [
  "DATABASE_URL — voice history & ratings (hosted by this deployment)",
  "R2_* — audio file storage (hosted by this deployment)",
  "POLAR_* — billing meters (hosted by this deployment)",
  "CLERK_* — sign-in only; skipped in guest mode",
] as const;
